POINTING_DEVICE_AUTO_MOUSE_ENABLE = yes

VIAL_AUTO_MOUSE_ENABLE = yes
VIAL_AUTO_MOUSE_LAYER_ENABLE = yes
MOUSEKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

POINTING_DEVICE_DRIVER = custom
POINTING_DEVICE_ENABLE = yes
SRC += paw3222.c
